### ISSUE TITLE
Improve the magic to generate the breadcrumb on tournament pages

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#106]
The breadcrumb generation currently uses the event slug, which may not always follow the pattern. 

![Image](https://github.com/india-ultimate/hub/assets/315678/8a205117-ac6a-4665-b93b-857f2394a79b)

We could directly use the event title. And if required strip the NCS + year prefix, if we really need to make the breadcrumb shorter.

**Comment by Joe2k** [comment]
The problem is that if the bread crumbs is too big it looks bad in mobile which is what everyone uses in the tournament. Hence should find a way to keep it super short

**Comment by punchagan** [comment]
![Image](https://github.com/india-ultimate/hub/assets/315678/db6faabc-f09d-4c28-ba98-8de4d4eb616a)


This could definitely use some improving. May be we need to add more logic to the crumb generation, if we want to be smart about it... using the title to start with, and adding some logic on top of it, seems like a good start.
