### ISSUE TITLE
Allow multiple MVPs and MSPs for a match

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#108]
Currently, a game can only have a single MVP/MSP per team. 

It should be easy to configure whether multiple MVPs/MSPs are allowed on each team - usually one per gender, but not necessarily(?)

**Comment by Joe2k** [comment]
Yep should revisit the model part as well and make sure we can see what all MSPs/MVPs a player has got over the years maybe in the future

**Comment by punchagan** [comment]
Being able to see all the MVPs/MSPs for a team or for the whole team would be a nice thing to have! It would make it easy to see things like who has the most MSPs for a team, in a tournament, etc.

**Comment by punchagan** [comment]
I think the spirit committee is pushing towards having a single MVP and MSP. We should help them push for this change, by leaving the UI as is.
