### ISSUE TITLE
Tournament Rules Page

### ISSUE THREAD

**Issue by Joe2k** [india-ultimate/hub#112]
Just like how we have a rules section in schedule sheet we need to have a rules page for each tournament

We can maybe have it as markdown and store it and render it easily in frontend without worrying about formatting and flexibility to have lists, headings etc.

**Comment by punchagan** [comment]
Sounds good. We can integrate a proper markdown editor for people to be able to enter and preview the markdown.

**Comment by Joe2k** [comment]
@punchagan Im anable to find a find a good markdown editor and preview for solidjs.. You have anything in mind?

**Comment by SibiAkkash** [comment]
lol i deleted @Joe2k's comment by mistake. He was telling that he wasn't able to find markdown editors for solid @punchagan
