### ISSUE TITLE
Scroll to Match Card when user tries to click on the match in overall view

### ISSUE THREAD

**Issue by Joe2k** [india-ultimate/hub#115]
We saw from beach nationals that there are a lot of dead clicks coming from the schedule page where users are trying to click on the badge on the top but nothing happens. We can make the badge clickable and when clicked we can scroll down to the match card which user clicked.
![Screenshot 2023-10-09 at 11 44 38 PM](https://github.com/india-ultimate/hub/assets/67282400/5af48afa-f2a8-4447-a446-f57fef932a43)

**Comment by AnishKacham** [comment]
Can pick this, will be easier once https://github.com/india-ultimate/hub/issues/116 is closed :3

**Comment by punchagan** [comment]
> Can pick this, will be easier once #116 is closed :3

If you need the fixture, you can just get the fixture from the branch and use it to get some test data. @Joe2k wants to trim down the fixture so that it's not so huge.

**Comment by punchagan** [comment]
@AnishKacham merged #127. So, you should now be able to use the fixture on `main`.

**Comment by Joe2k** [comment]
@AnishKacham raise PR fast fast xD

**Comment by AnishKacham** [comment]
This isn't pushed to prod yet @punchagan ? Don't see the feature 🙃

**Comment by Joe2k** [comment]
hehe he might have not deployed it yet

**Comment by punchagan** [comment]
> This isn't pushed to prod yet @punchagan ? Don't see the feature 🙃

Deployed now! :)
