### ISSUE TITLE
Add a fixture to easily populate a tournament

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#116]
To make the lives of developers easier, add a fixture to easily populate a tournament in the development environment. We could also populate other things like a few players, etc. 

This fixture can also be used for unit tests, integration tests, etc.

**Comment by Joe2k** [comment]
@punchagan feel free to close this. Im actually afk for this weekend. I will change this if needed when I pick up the unit tests. Merging this will unblock other devs i think
