### ISSUE TITLE
Include spirit scores in the team view

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#120]
The team view makes it easy to see all the scores of a team, in the tournament. A similar view for spirit scores would be nice. We could also include spirit scores in the same list...

![Image](https://github.com/india-ultimate/hub/assets/315678/a5aa8a1b-be78-4dc8-8b1d-0f1f1a7e678c)

We currently show a button that links to the spirit scores, but we might be able to show a summary view of the spirit scores too. (See [windmill site](https://www.windmilltournament.com/legacy), for instance)

![Image](https://github.com/india-ultimate/hub/assets/315678/1b5f7b5a-d92e-41fe-9dac-2ed9c0555e17)

**Comment by varunshah0** [comment]
Can we add a new column to the SpiritScore model?

**Comment by Joe2k** [comment]
@varunshah0 column to store the total score you mean?

**Comment by slice-varuns** [comment]
Yes a column for total score which we can use to display directly. Otherwise it would require real time computation.

**Comment by Joe2k** [comment]
yep you can do that

**Comment by punchagan** [comment]
@Joe2k thanks for responding on this one!

**Comment by SibiAkkash** [comment]
@Joe2k shall we move the team logos to the center, to fix the spacing issues we have in the match card ?
Current: 
![image](https://github.com/india-ultimate/hub/assets/39093537/499caef9-cefe-4733-859c-9b258abccbf9)
We have uneven gaps as the team names are different lengths. Pushing team logos to center could be a quick fix

Proposed: 
![image](https://github.com/india-ultimate/hub/assets/39093537/c3bd3f77-d502-450f-be41-a3b8bb74776e)
