### ISSUE TITLE
Make the phone numbers on the transaction validation page to be WA links

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#123]
Currently, we just show the phone number. They could be made into URL that use the WA api to be able to directly send messages to those numbers on clicking them...

**Comment by AnishKacham** [comment]
I can pick this up :3

**Comment by Joe2k** [comment]
@AnishKacham gg.. Just put a jist of which API and all you planning to integrate here just before implementing along with their docs and references maybe

**Comment by AnishKacham** [comment]
> @AnishKacham gg.. Just put a jist of which API and all you planning to integrate here just before implementing along with their docs and references maybe

APIs huh. I thought this would be a simple frontend fix where I wrap the phone number where ever it is rendered with 
`<a href="https://api.whatsapp.com/send?phone=XXXXXXXXXX">{PHONE_NO}</a>`.

Of course have to check the format of the phone number we're currently storing.

**Comment by punchagan** [comment]
Yes, this is good enough for now! You can make this a utility so that, we can start by displaying phone numbers of captains, for #121 instead of completely automating it, before we do proper APIs for that to automate the reminders.

**Comment by punchagan** [comment]
> Of course have to check the format of the phone number we're currently storing.

The phone numbers are stored with the country code prefixed. `+919988776655`, for example.
