### ISSUE TITLE
Drag and drop to update seeding

### ISSUE THREAD

**Issue by SibiAkkash** [india-ultimate/hub#155]
Currently users have to write out JSON to update the seeding. A drag and drop system to reorder seeding would be better.

**Comment by Joe2k** [comment]
@SibiAkkash Hey when are you planning to pick this up? We are planning to give a demo to competitions commitee peeps on Saturday. So would be great to have this ready by then xD

**Comment by SibiAkkash** [comment]
Ah, let me sit on this tonight, will give an update then ?
