### ISSUE TITLE
Ensure email IDs are case insensitive

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#165]
- [ ] Change all email IDs and usernames in the DB to lower case
- [ ] Ensure any email ID inputs are used in lower case, when looking for users, etc.

**Comment by SibiAkkash** [comment]
1. Just a data migration would have to be written for changing emails IDs and usernames to be lower case right ? I can take this up

**Comment by punchagan** [comment]
Yes, that's correct, for 1.  

For 2, we need to ensure we use lower cased email IDs when receiving them from different API calls, like login, registration, signup, etc. 

Ideally, we want to deploy both the changes together, so we don't leave some users in a weird state.

**Comment by punchagan** [comment]
I guess for the first part, we'd need to do some manual work to "merge" accounts, since we require usernames to be unique - if a user already has two accounts in the DB with and without capital letters, we won't simply be able to convert the usernames and emails to lowercase. 

I'll look at the production DB and see what needs to be done. @SibiAkkash If you can send a PR for 2, that would be great. While you are at it, can you also make sure that there are not leading and trailing spaces too? Thanks!

**Comment by SibiAkkash** [comment]
> I guess for the first part, we'd need to do some manual work to "merge" accounts, since we require usernames to be unique - if a user already has two accounts in the DB with and without capital letters, we won't simply be able to convert the usernames and emails to lowercase.
> 
> I'll look at the production DB and see what needs to be done. @SibiAkkash If you can send a PR for 2, that would be great. While you are at it, can you also make sure that there are not leading and trailing spaces too? Thanks!

sure, i'll work on a PR for 2

**Comment by punchagan** [comment]
Closed with #168 #194 and #203
