### ISSUE TITLE
Show match day in schedule

### ISSUE THREAD

**Issue by SibiAkkash** [india-ultimate/hub#186]
I think it'll be good to show the day of the match along with field number and time
@Joe2k @punchagan 
![image](https://github.com/india-ultimate/hub/assets/39093537/5f2e3bae-861d-4a7a-9c67-f6b2ca16d496)

**Comment by Joe2k** [comment]
Hmm didnt get you? Whats different here in the screenshot?

**Comment by Joe2k** [comment]
Oh ok you are suggesting to show the day along with time.. Yes yes that should be added i think

**Comment by SibiAkkash** [comment]
CFT vs Airborne is on Day 2 right ? Right now its shown as just 7:30 AM.
Mayve its better to show as Field 4 | Day 2 | 7:30 AM

**Comment by Joe2k** [comment]
Or this is a problem only in Teams page right..Cause in schedule page we already show one day at a time..

So in teams page we can have sections day wise and show matches of one day in every Section namely Day 1, Day2 etc

**Comment by SibiAkkash** [comment]
correct, i wanted to look at all matches for CFT. Its already ordered by day only, Day 2 comes after only, but it might be easier to read if we show day explicitly

**Comment by SibiAkkash** [comment]
> Or this is a problem only in Teams page right..Cause in schedule page we already show one day at a time..
> 
> So in teams page we can have sections day wise and show matches of one day in every Section namely Day 1, Day2 etc
> 
> That might make more sense as having Field 4 | Day 2 | 7:30 AM might be too long for mobile view

yeah we can have day wise sections

**Comment by Joe2k** [comment]
perfect.. lets do that then
