### ISSUE TITLE
Remember logged in status

### ISSUE THREAD

**Issue by SibiAkkash** [india-ultimate/hub#197]
Currently users get logged out when the page is refreshed. While team admins are adding scores through the day, they'd have to login multiple times.

If we can remember login for 2-3 days (typical tournament duration), it'll reduce number of times users have to login during tournaments

**Comment by punchagan** [comment]
I agree, but I thought Django sessions by default had a 2 week validity. May be we need to setup something for that, but this is definitely worth investigating and fixing!

**Comment by SibiAkkash** [comment]
Oh. When I refresh the page on mobile, it's logging me out

**Comment by Joe2k** [comment]
Huh this is weird... I did see this happen with some people but for me I am logged in for a week

**Comment by SibiAkkash** [comment]
This can be closed i think ? @punchagan @Joe2k

**Comment by punchagan** [comment]
Yes, please. In future just add it in your commit message so that things get closed automatically.
