### ISSUE TITLE
Show a teams overall spirit scores for all games when clicked on teams name in Spirit ranking

### ISSUE THREAD

**Issue by Joe2k** [india-ultimate/hub#201]
Show a teams overall spirit scores for all games when clicked on teams name in Spirit ranking in modal

Like

vs NFZ 2 2 2 2 3
vs L2f 2 1 2 3 2 2

**Comment by Joe2k** [comment]
I think we dont need this if we have #120 

Thougths @SibiAkkash @punchagan

**Comment by SibiAkkash** [comment]
Yeah #120 would fix this issue

**Comment by SibiAkkash** [comment]
Yeah #120 would fix this issue
