### ISSUE TITLE
Add a "go to top" button in tournament schedule page

### ISSUE THREAD

**Issue by SibiAkkash** [india-ultimate/hub#207]
Adding such a button would avoid having to scroll a long way up to get to the schedule

**Comment by Joe2k** [comment]
This should also solve this i think:
"The navigation could be better with may be a menu of options accessible and freeze-paned. Integration with earlier upai portal was not seamless, but the must be just the initial hiccup. Having said that, I liked the hub."

**Comment by Joe2k** [comment]
@SibiAkkash Did you implement this already in any PR? I thought this was not picked so made a pr for this

**Comment by SibiAkkash** [comment]
> @SibiAkkash Did you implement this already in any PR? I thought this was not picked so made a pr for this

No, haven't taken this up yet. You can take this if you want to :)

**Comment by Joe2k** [comment]
Cool raised PR already
