### ISSUE TITLE
Remove sequence number field from pool models

### ISSUE THREAD

**Issue by SibiAkkash** [india-ultimate/hub#216]
The `sequence_number` field in pool models . The field denotes the pool's number, in that tournament. Its being used for giving different colors to pool matches, in the UI. 

https://upai.zulipchat.com/#narrow/stream/387757-tech-backend/topic/tournament.20algo/near/404345115

**Comment by punchagan** [comment]
Can you write up an explanation of why? If there was a discussion about this on Zulip or another issue, linking to that would be helpful too.
