### ISSUE TITLE
Bug: Team Page Matches Group By Date is wrong

### ISSUE THREAD

**Issue by Joe2k** [india-ultimate/hub#221]
Currently we are showing matches on diff days in diff section. But naming of section is wrong.

For ex. If Team A plays only from Day 2, the team page will still show Day 2 matches under Day 1 and Day3 matches under Day 2

**Comment by Joe2k** [comment]
Happening currently in prod for Surat Qualifiers
![Screenshot 2023-12-05 at 6 11 27 PM](https://github.com/india-ultimate/hub/assets/67282400/31a20b09-17a2-4476-a858-6103f37e1971)
![Screenshot 2023-12-05 at 7 40 17 PM](https://github.com/india-ultimate/hub/assets/67282400/bfab1980-30df-4b5b-8381-4d218074a6fb)


cc: @SibiAkkash

**Comment by SibiAkkash** [comment]
ah damn, fixing now. Also, is day 1 schedule empty  for Surat qualifiers ?

**Comment by Joe2k** [comment]
Yes correct.. So they have only one day tournament on Sunday

**Comment by Joe2k** [comment]
Actually its not a hurry.. Its actually good for surat peeps now as they have only one day anyway xD... Just wanted to point it out before i forget.. you can work on it whenver posible but not urgent

**Comment by SibiAkkash** [comment]
> Yes correct.. So they have only one day tournament on Sunday

oh, then why do we have Day 1 and Day 2 if Day 1 is empty :thinking:

**Comment by SibiAkkash** [comment]
> Actually its not a hurry.. Its actually good for surat peeps now as they have only one day anyway xD... Just wanted to point it out before i forget.. you can work on it whenver posible but not urgent

Hmm, so if its a 1 day tournament, we shouldn't show the day itself then

**Comment by Joe2k** [comment]
Yeah ideally we shoudnt show Day 1 if day 1 is empty but I take the event.start and end date as source of truth and show all days between that without checking if matches are there for the day

**Comment by SibiAkkash** [comment]
> Yeah ideally we shoudnt show Day 1 if day 1 is empty but I take the event.start and end date as source of truth and show all days between that without checking if matches are there for the day

oh ok, so if there's only matches on "day 2" why does the tournament start date on saturday then ?

**Comment by Joe2k** [comment]
Its because on UC they have the event start and end dates like that
