### ISSUE TITLE
Mask person name in the fixtures dump

### ISSUE THREAD

**Issue by SibiAkkash** [india-ultimate/hub#255]
We have first name and last name in `fixtures/sample.json`. I think it should be masked like the email, for privacy concerns. Thoughts @Joe2k @punchagan

**Comment by punchagan** [comment]
The website itself is public. So, we thought it doesn't really matter. But, if you'd like to mask them, go for it. :)

**Comment by SibiAkkash** [comment]
Makes sense, probably not worth masking names
