### ISSUE TITLE
Reduce UC Questions

### ISSUE THREAD

**Issue by Joe2k** [india-ultimate/hub#272]
- Show UC Email to the user in UC Linking Page
- Show email in dropdown / tooltip in validate roster page

**Comment by punchagan** [comment]
Logins to the Hub are not really monitored and I'm a little wary, but, both pages are behind login. Might be okay.

**Comment by Joe2k** [comment]
Yeah even I was a bit concerend but dont we anyway see the email IDs in UC when rostering already? So thought it should be fine
