### ISSUE TITLE
Uploading files from Google Drive and such doesn't work

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#274]
Oops! An error occurred while submitting accreditation data: TypeError: Load failed

**Comment by punchagan** [comment]
May be as a stop gap solution, show a message to try uploading from the device, when we see this error message? Or just fix the issue itself, if it's easy to fix.

**Comment by Joe2k** [comment]
[Can try implementing this](https://stackoverflow.com/questions/57516930/prevent-html-file-input-from-selecting-files-in-google-drive-while-using-android)

**Comment by Joe2k** [comment]
But I cant test it as I dont have android xD

**Comment by punchagan** [comment]
> But I cant test it as I dont have android xD

Stop showing off! XD

If you can push to staging, or as a branch, one of us can test it.

**Comment by punchagan** [comment]
Closed in #273
