### ISSUE TITLE
Add navigation back to dashboard from user actions pages

### ISSUE THREAD

**Issue by punchagan** [india-ultimate/hub#80]
On a mobile device the nav menu is shown only on clicking the hamburger icon, and navigating to the Dashboard is two clicks away. It may be useful to add easier navigation (at least on pages without the Status Stepper?) for users to be able to navigate back to the Dashboard quickly.

**Comment by Joe2k** [comment]
We should implement bread crumbs here i guess.. will help users to keep track of their journey and any parent page will be a click away

**Comment by punchagan** [comment]
Sure, that works! :)

**Comment by Joe2k** [comment]
I will work on this and send PR by tomorrow
