### ISSUE TITLE
Refreshing any Page takes the user back to login page and then back to the current page for Logged in users

### ISSUE THREAD

**Issue by Joe2k** [india-ultimate/hub#84]
https://github.com/india-ultimate/hub/assets/67282400/b0cb8caa-2060-4948-8e60-62c31e9a9f0f

**Comment by Joe2k** [comment]
@punchagan Im thinking of adding a `userFetchedOnce` flag also in store and toggle it when the first request to get user succeeds. And only when `userFetchedOnce` is true and user is not logged in we can navigate them back to Login screen.

What do you think? You have any better ideas?

Another way is totally moving this to use sokid-query and fetching user through that remove user from global store. That will give us fetching, error and data directly

**Comment by punchagan** [comment]
yeah, if you have the patience to do it the right way, I'd prefer doing it using `solid-query`. Fix it once and for all. :)

**Comment by Joe2k** [comment]
Cool will do!
